// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/auth.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Identity struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Identity) Reset()         { *m = Identity{} }
func (m *Identity) String() string { return proto.CompactTextString(m) }
func (*Identity) ProtoMessage()    {}
func (*Identity) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9d38a2cdbb4f144, []int{0}
}

func (m *Identity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Identity.Unmarshal(m, b)
}
func (m *Identity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Identity.Marshal(b, m, deterministic)
}
func (m *Identity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Identity.Merge(m, src)
}
func (m *Identity) XXX_Size() int {
	return xxx_messageInfo_Identity.Size(m)
}
func (m *Identity) XXX_DiscardUnknown() {
	xxx_messageInfo_Identity.DiscardUnknown(m)
}

var xxx_messageInfo_Identity proto.InternalMessageInfo

func (m *Identity) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Identity) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type Token struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Token) Reset()         { *m = Token{} }
func (m *Token) String() string { return proto.CompactTextString(m) }
func (*Token) ProtoMessage()    {}
func (*Token) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9d38a2cdbb4f144, []int{1}
}

func (m *Token) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Token.Unmarshal(m, b)
}
func (m *Token) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Token.Marshal(b, m, deterministic)
}
func (m *Token) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Token.Merge(m, src)
}
func (m *Token) XXX_Size() int {
	return xxx_messageInfo_Token.Size(m)
}
func (m *Token) XXX_DiscardUnknown() {
	xxx_messageInfo_Token.DiscardUnknown(m)
}

var xxx_messageInfo_Token proto.InternalMessageInfo

func (m *Token) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type Validated struct {
	Valid                bool     `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Validated) Reset()         { *m = Validated{} }
func (m *Validated) String() string { return proto.CompactTextString(m) }
func (*Validated) ProtoMessage()    {}
func (*Validated) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9d38a2cdbb4f144, []int{2}
}

func (m *Validated) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Validated.Unmarshal(m, b)
}
func (m *Validated) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Validated.Marshal(b, m, deterministic)
}
func (m *Validated) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Validated.Merge(m, src)
}
func (m *Validated) XXX_Size() int {
	return xxx_messageInfo_Validated.Size(m)
}
func (m *Validated) XXX_DiscardUnknown() {
	xxx_messageInfo_Validated.DiscardUnknown(m)
}

var xxx_messageInfo_Validated proto.InternalMessageInfo

func (m *Validated) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

type PublicKeyRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PublicKeyRequest) Reset()         { *m = PublicKeyRequest{} }
func (m *PublicKeyRequest) String() string { return proto.CompactTextString(m) }
func (*PublicKeyRequest) ProtoMessage()    {}
func (*PublicKeyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9d38a2cdbb4f144, []int{3}
}

func (m *PublicKeyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublicKeyRequest.Unmarshal(m, b)
}
func (m *PublicKeyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublicKeyRequest.Marshal(b, m, deterministic)
}
func (m *PublicKeyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublicKeyRequest.Merge(m, src)
}
func (m *PublicKeyRequest) XXX_Size() int {
	return xxx_messageInfo_PublicKeyRequest.Size(m)
}
func (m *PublicKeyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PublicKeyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PublicKeyRequest proto.InternalMessageInfo

type PublicKey struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PublicKey) Reset()         { *m = PublicKey{} }
func (m *PublicKey) String() string { return proto.CompactTextString(m) }
func (*PublicKey) ProtoMessage()    {}
func (*PublicKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9d38a2cdbb4f144, []int{4}
}

func (m *PublicKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublicKey.Unmarshal(m, b)
}
func (m *PublicKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublicKey.Marshal(b, m, deterministic)
}
func (m *PublicKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublicKey.Merge(m, src)
}
func (m *PublicKey) XXX_Size() int {
	return xxx_messageInfo_PublicKey.Size(m)
}
func (m *PublicKey) XXX_DiscardUnknown() {
	xxx_messageInfo_PublicKey.DiscardUnknown(m)
}

var xxx_messageInfo_PublicKey proto.InternalMessageInfo

func (m *PublicKey) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func init() {
	proto.RegisterType((*Identity)(nil), "auth.Identity")
	proto.RegisterType((*Token)(nil), "auth.Token")
	proto.RegisterType((*Validated)(nil), "auth.Validated")
	proto.RegisterType((*PublicKeyRequest)(nil), "auth.PublicKeyRequest")
	proto.RegisterType((*PublicKey)(nil), "auth.PublicKey")
}

func init() { proto.RegisterFile("proto/auth.proto", fileDescriptor_a9d38a2cdbb4f144) }

var fileDescriptor_a9d38a2cdbb4f144 = []byte{
	// 276 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x86, 0xdb, 0xd8, 0x4a, 0x32, 0x96, 0x1a, 0x06, 0x91, 0x12, 0x28, 0xe8, 0x22, 0x22, 0x42,
	0x13, 0x50, 0x10, 0x3c, 0xea, 0x45, 0xc4, 0x8b, 0x04, 0xf1, 0xe0, 0x6d, 0x93, 0x5d, 0xcc, 0xda,
	0x34, 0x1b, 0x93, 0x89, 0x25, 0xef, 0xe2, 0xc3, 0xca, 0x6e, 0x9a, 0x28, 0x9e, 0xe6, 0xff, 0x26,
	0x33, 0xe1, 0x9b, 0x05, 0xbf, 0xac, 0x34, 0xe9, 0x88, 0x37, 0x94, 0x85, 0x36, 0xe2, 0xc4, 0x64,
	0x76, 0x03, 0xee, 0xa3, 0x90, 0x05, 0x29, 0x6a, 0x71, 0x0e, 0x8e, 0x12, 0x8b, 0xf1, 0xc9, 0xf8,
	0xc2, 0x8b, 0x1d, 0x25, 0x30, 0x00, 0xb7, 0xe4, 0x75, 0xbd, 0xd5, 0x95, 0x58, 0x38, 0xb6, 0x3b,
	0x30, 0x5b, 0xc2, 0xf4, 0x45, 0xaf, 0x65, 0x81, 0x47, 0x30, 0x25, 0x13, 0x76, 0x7b, 0x1d, 0xb0,
	0x53, 0xf0, 0x5e, 0x79, 0xae, 0x04, 0x27, 0x29, 0xcc, 0xc8, 0x97, 0x01, 0x3b, 0xe2, 0xc6, 0x1d,
	0x30, 0x04, 0xff, 0xb9, 0x49, 0x72, 0x95, 0x3e, 0xc9, 0x36, 0x96, 0x9f, 0x8d, 0xac, 0x89, 0x2d,
	0xc1, 0x1b, 0x7a, 0xe8, 0xc3, 0xde, 0x5a, 0xb6, 0xbb, 0xff, 0x9a, 0x78, 0xf5, 0x3d, 0x86, 0xc9,
	0x5d, 0x43, 0x19, 0xae, 0x60, 0x66, 0xaa, 0xf1, 0x4e, 0x39, 0x49, 0x9c, 0x87, 0xf6, 0xb0, 0xfe,
	0x92, 0xe0, 0xa0, 0x63, 0x6b, 0xc8, 0x46, 0x78, 0x09, 0x6e, 0x6f, 0x83, 0x7f, 0x3f, 0x05, 0x87,
	0x1d, 0x0c, 0xaa, 0x6c, 0x84, 0xb7, 0x30, 0x7b, 0x90, 0xf4, 0x6b, 0x71, 0xdc, 0x8d, 0xfc, 0x57,
	0xed, 0x57, 0x87, 0x3e, 0x1b, 0xdd, 0x9f, 0xbf, 0x9d, 0xbd, 0x2b, 0xca, 0x9a, 0x24, 0x4c, 0xf5,
	0x26, 0x52, 0x05, 0xd7, 0x99, 0xaa, 0x74, 0xf4, 0xb1, 0xa5, 0x55, 0xcd, 0x37, 0x65, 0x2e, 0x23,
	0xfb, 0xf2, 0xc9, 0xbe, 0x2d, 0xd7, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x2e, 0x45, 0x4e, 0x3d,
	0x94, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AuthClient is the client API for Auth service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AuthClient interface {
	// Obtains the token
	Authenticate(ctx context.Context, in *Identity, opts ...grpc.CallOption) (*Token, error)
	// Validate the token with public key
	Validate(ctx context.Context, in *Token, opts ...grpc.CallOption) (*Validated, error)
	// Obtains the public key to validate the token
	GetPublicKey(ctx context.Context, in *PublicKeyRequest, opts ...grpc.CallOption) (*PublicKey, error)
}

type authClient struct {
	cc *grpc.ClientConn
}

func NewAuthClient(cc *grpc.ClientConn) AuthClient {
	return &authClient{cc}
}

func (c *authClient) Authenticate(ctx context.Context, in *Identity, opts ...grpc.CallOption) (*Token, error) {
	out := new(Token)
	err := c.cc.Invoke(ctx, "/auth.Auth/Authenticate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) Validate(ctx context.Context, in *Token, opts ...grpc.CallOption) (*Validated, error) {
	out := new(Validated)
	err := c.cc.Invoke(ctx, "/auth.Auth/Validate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) GetPublicKey(ctx context.Context, in *PublicKeyRequest, opts ...grpc.CallOption) (*PublicKey, error) {
	out := new(PublicKey)
	err := c.cc.Invoke(ctx, "/auth.Auth/GetPublicKey", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServer is the server API for Auth service.
type AuthServer interface {
	// Obtains the token
	Authenticate(context.Context, *Identity) (*Token, error)
	// Validate the token with public key
	Validate(context.Context, *Token) (*Validated, error)
	// Obtains the public key to validate the token
	GetPublicKey(context.Context, *PublicKeyRequest) (*PublicKey, error)
}

// UnimplementedAuthServer can be embedded to have forward compatible implementations.
type UnimplementedAuthServer struct {
}

func (*UnimplementedAuthServer) Authenticate(ctx context.Context, req *Identity) (*Token, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Authenticate not implemented")
}
func (*UnimplementedAuthServer) Validate(ctx context.Context, req *Token) (*Validated, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Validate not implemented")
}
func (*UnimplementedAuthServer) GetPublicKey(ctx context.Context, req *PublicKeyRequest) (*PublicKey, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPublicKey not implemented")
}

func RegisterAuthServer(s *grpc.Server, srv AuthServer) {
	s.RegisterService(&_Auth_serviceDesc, srv)
}

func _Auth_Authenticate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Identity)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).Authenticate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.Auth/Authenticate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).Authenticate(ctx, req.(*Identity))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_Validate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Token)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).Validate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.Auth/Validate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).Validate(ctx, req.(*Token))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_GetPublicKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublicKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).GetPublicKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.Auth/GetPublicKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).GetPublicKey(ctx, req.(*PublicKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Auth_serviceDesc = grpc.ServiceDesc{
	ServiceName: "auth.Auth",
	HandlerType: (*AuthServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Authenticate",
			Handler:    _Auth_Authenticate_Handler,
		},
		{
			MethodName: "Validate",
			Handler:    _Auth_Validate_Handler,
		},
		{
			MethodName: "GetPublicKey",
			Handler:    _Auth_GetPublicKey_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/auth.proto",
}
